name: Generar PDFs con imágenes (Runware)

on:
  push:
    paths:
      - 'historias/*.md'
      - 'historias/**/*.md'
      - 'scripts/**'
      - '.github/workflows/generar-pdfs-comic.yml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  generar_pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar fuente DejaVu (Unicode)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core

      - name: Generar PDFs (toda la carpeta historias)
        env:
          FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
          IMAGEROUTER_PROVIDER: runware
          RUNWARE_API_URL: https://api.runware.ai/v1
          RUNWARE_API_KEY: ${{ secrets.RUNWARE_API_KEY }}
          RUNWARE_MODEL: runware:101@1
          PROMPT_STYLE: neutral
          MAX_IMAGES: '4'
        run: |
          mkdir -p pdfs_generados
          python scripts/generar_pdfs_comic.py --input-folder historias --output-folder pdfs_generados

      - name: Listar PDFs generados
        run: |
          find pdfs_generados -type f -name '*.pdf' -print || true

      - name: Subir PDFs como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: pdfs-comic-${{ github.run_number }}-${{ github.sha }}
          path: |
            pdfs_generados/**/*.pdf
            pdfs_generados/*.pdf
          if-no-files-found: error
