name: Generar PDFs tipo cómic (CI rápido)

on:
  push:
    paths:
      - 'historias/*.md'
      - 'historias/**/*.md'
      - 'scripts/generar_pdfs_comic.py'
      - '.github/workflows/generar-pdfs-comic.yml'
      - 'requirements.txt'

jobs:
  generar_pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Instalar dependencias (mínimas, sin SD)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar fuente DejaVu Sans (Unicode)
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-dejavu-core
          ls -l /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf || true

      - name: Detectar archivos .md cambiados
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: |
            historias/*.md
            historias/**/*.md
          separator: " "

      - name: Generar PDFs (modo rápido con placeholders)
        env:
          FAST_MODE: '1'
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
        run: |
          mkdir -p pdfs_generados
          CHANGED="${{ steps.changed.outputs.all_changed_files }}"
          echo "Archivos MD cambiados: '$CHANGED'"
          if [ -z "$CHANGED" ]; then
            echo "Sin lista de cambios; procesando todo 'historias/'"
            python scripts/generar_pdfs_comic.py --input-folder historias --output-folder pdfs_generados
          else
            echo "Procesando archivos modificados:"
            echo "$CHANGED"
            python scripts/generar_pdfs_comic.py --output-folder pdfs_generados $CHANGED
          fi

      - name: Listar PDFs generados
        id: listpdfs
        run: |
          echo "Contenido de pdfs_generados/:"
          ls -la pdfs_generados || true
          echo "Listado recursivo de PDFs:"
          find pdfs_generados -type f -name '*.pdf' -print || true
          COUNT=$(find pdfs_generados -type f -name '*.pdf' 2>/dev/null | wc -l || true)
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Subir PDFs como artefacto
        if: steps.listpdfs.outputs.count != '0'
        uses: actions/upload-artifact@v4
        with:
          name: pdfs-comic
          path: |
            pdfs_generados/*.pdf
            pdfs_generados/**/*.pdf
          if-no-files-found: error


