# .github/workflows/generar-pdfs-comic.yml
name: Generar PDFs (fallback AI Horde)

on:
  push:
    paths:
      - 'historias/**/*.md'
      - 'scripts/**'
      - '.github/workflows/generar-pdfs-comic.yml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  generar_pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar PDFs ilustrados (AI Horde)
        env:
          FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf

          # Proveedor gratuito
          IMAGEROUTER_PROVIDER: aihorde
          IMAGEROUTER_BASE_URL: https://aihorde.net/api/v2
          # IMAGEROUTER_API_KEY: ""  # opcional; por defecto usa "0000000000"
          MAX_IMAGES: '4'
        run: |
          mkdir -p pdfs_generados
          python scripts/generar_pdfs_comic.py --input-folder historias --output-folder pdfs_generados

      - name: Subir PDFs como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: pdfs-comic
          path: |
            pdfs_generados/**/*.pdf
            pdfs_generados/*.pdf
          if-no-files-found: error
