# .github/workflows/generar-pdfs-comic.yml
name: Generar PDFs con imágenes (Runware)

on:
  push:
    paths:
      - 'historias/**/*.md'
      - 'scripts/**'
      - '.github/workflows/generar-pdfs-comic.yml'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  generar_pdfs:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generar PDFs ilustrados
        env:
          FONT_PATH: /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
          IMAGEROUTER_PROVIDER: runware
          RUNWARE_API_URL: https://api.runware.ai/v1
          RUNWARE_API_KEY: ${{ secrets.RUNWARE_API_KEY }}
          IMAGEROUTER_MODEL: runware:101@1
          RUNWARE_MODEL: runware:101@1
          MAX_IMAGES: '6'
        run: |
          mkdir -p pdfs_generados
          python scripts/generar_pdfs_comic.py --input-folder historias --output-folder pdfs_generados

      - name: Subir PDFs como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: pdfs-comic
          path: |
            pdfs_generados/**/*.pdf
            pdfs_generados/*.pdf
          if-no-files-found: error
